fix typos

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,14 +63,14 @@ jobs:
           command: |
             echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"
             ls -l ~/.ssh/id_rsa || true
-            ssh-keygen -y -f ~/.ssh/id_rsa || echo "INVALID KEY
+            ssh-keygen -y -f ~/.ssh/id_rsa || echo "INVALID KEY"
       
       - run:
           name: Setup SSH
           command: |
             set -x
             mkdir -p ~/.ssh
-            printf '%s' "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
+            echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
             chmod 600 ~/.ssh/id_rsa
             
             EC2_IP=$(cat /tmp/ec2_ip.txt)
